package com.rj1399.customersupport.service;
import com.rj1399.customersupport.api.ApiDtos; import com.rj1399.customersupport.domain.*; import com.rj1399.customersupport.repository.*;
import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal; import java.time.*; import java.time.temporal.ChronoUnit; import java.util.UUID;
@Service public class CustomerSupportService {
 public static final int REFUND_MINIMUM_DELAY_DAYS=3; public static final BigDecimal MAX_AUTOMATIC_REFUND=new BigDecimal("5000.00");
 private final CustomerRepository customers; private final OrderRepository orders; private final PaymentRepository payments; private final RefundRepository refunds; private final SupportTicketRepository tickets; private final Clock clock;
 public CustomerSupportService(CustomerRepository customers,OrderRepository orders,PaymentRepository payments,RefundRepository refunds,SupportTicketRepository tickets,Clock clock){this.customers=customers;this.orders=orders;this.payments=payments;this.refunds=refunds;this.tickets=tickets;this.clock=clock;}
 @Transactional(readOnly=true) public ApiDtos.CustomerResponse getCustomer(UUID id){Customer c=customers.findById(id).orElseThrow(()->notFound("Customer",id.toString()));return new ApiDtos.CustomerResponse(c.getId(),c.getName(),c.getEmail(),c.getCreatedAt());}
 @Transactional(readOnly=true) public ApiDtos.OrderResponse getOrder(String n){Order o=findOrder(n);return order(o);}
 @Transactional(readOnly=true) public ApiDtos.DeliveryResponse getDelivery(String n){Order o=findOrder(n);return new ApiDtos.DeliveryResponse(o.getOrderNumber(),o.getStatus().name(),o.getExpectedDeliveryDate(),o.getDeliveredDate(),daysLate(o));}
 @Transactional(readOnly=true) public ApiDtos.PaymentResponse getPayment(String n){Order o=findOrder(n);Payment p=payments.findByOrderId(o.getId()).orElseThrow(()->notFound("Payment for order",n));return new ApiDtos.PaymentResponse(p.getId(),p.getPaymentReference(),n,p.getAmount(),p.getStatus().name());}
 @Transactional(readOnly=true) public ApiDtos.RefundPolicyResponse checkRefundPolicy(String n){Order o=findOrder(n);Payment p=payments.findByOrderId(o.getId()).orElseThrow(()->notFound("Payment for order",n));boolean ok=daysLate(o)>=REFUND_MINIMUM_DELAY_DAYS&&p.getStatus()==Payment.Status.CAPTURED&&!refunds.existsByOrderIdAndStatus(o.getId(),Refund.Status.COMPLETED);return new ApiDtos.RefundPolicyResponse(ok,REFUND_MINIMUM_DELAY_DAYS,MAX_AUTOMATIC_REFUND,ok?"Eligible: delivery delay meets policy and payment is captured.":"Not eligible: delay, payment status, or existing refund does not satisfy policy.");}
 @Transactional public ApiDtos.RefundResponse createRefund(ApiDtos.RefundRequest r){Refund existing=refunds.findByIdempotencyKey(r.idempotencyKey()).orElse(null);if(existing!=null)return refund(existing);Order o=findOrder(r.orderNumber());Payment p=payments.findByOrderId(o.getId()).orElseThrow(()->notFound("Payment for order",r.orderNumber()));long late=daysLate(o);if(late<REFUND_MINIMUM_DELAY_DAYS)throw new BusinessRuleException("REFUND_NOT_ELIGIBLE","Order "+o.getOrderNumber()+" is only "+late+" day(s) late; policy requires "+REFUND_MINIMUM_DELAY_DAYS+" days.");if(p.getStatus()!=Payment.Status.CAPTURED)throw new BusinessRuleException("REFUND_NOT_ELIGIBLE","Payment is not in CAPTURED state.");if(o.getTotalAmount().compareTo(MAX_AUTOMATIC_REFUND)>0)throw new BusinessRuleException("HUMAN_APPROVAL_REQUIRED","Refund exceeds the automatic refund limit of "+MAX_AUTOMATIC_REFUND+".");if(refunds.existsByOrderIdAndStatus(o.getId(),Refund.Status.COMPLETED))throw new BusinessRuleException("REFUND_ALREADY_COMPLETED","A completed refund already exists for this order.");Refund x=new Refund("RF-"+UUID.randomUUID().toString().substring(0,8).toUpperCase(),r.idempotencyKey(),o,o.getTotalAmount(),r.reason(),Refund.Status.COMPLETED);return refund(refunds.save(x));}
 @Transactional public ApiDtos.TicketResponse createTicket(ApiDtos.TicketRequest r){Customer c=customers.findById(r.customerId()).orElseThrow(()->notFound("Customer",r.customerId().toString()));Order o=r.orderId()==null?null:orders.findById(r.orderId()).orElseThrow(()->notFound("Order",r.orderId().toString()));SupportTicket t=new SupportTicket("TKT-"+UUID.randomUUID().toString().substring(0,8).toUpperCase(),c,o,r.subject(),r.description(),SupportTicket.Status.OPEN);return ticket(tickets.save(t));}
 @Transactional(readOnly=true) public ApiDtos.TicketResponse getTicket(String n){return ticket(tickets.findByTicketNumber(n).orElseThrow(()->notFound("Ticket",n)));}
 private Order findOrder(String n){return orders.findByOrderNumber(n).orElseThrow(()->notFound("Order",n));} private long daysLate(Order o){LocalDate end=o.getDeliveredDate()!=null?o.getDeliveredDate():LocalDate.now(clock);return Math.max(0,ChronoUnit.DAYS.between(o.getExpectedDeliveryDate(),end));}
 private ApiDtos.OrderResponse order(Order o){return new ApiDtos.OrderResponse(o.getId(),o.getOrderNumber(),o.getCustomer().getId(),o.getTotalAmount(),o.getStatus().name(),o.getExpectedDeliveryDate(),o.getDeliveredDate(),daysLate(o));} private ApiDtos.RefundResponse refund(Refund r){return new ApiDtos.RefundResponse(r.getId(),r.getRefundReference(),r.getOrder().getOrderNumber(),r.getAmount(),r.getReason(),r.getStatus().name(),r.getCreatedAt());} private ApiDtos.TicketResponse ticket(SupportTicket t){return new ApiDtos.TicketResponse(t.getId(),t.getTicketNumber(),t.getCustomer().getId(),t.getOrder()==null?null:t.getOrder().getOrderNumber(),t.getSubject(),t.getDescription(),t.getStatus().name(),t.getCreatedAt());}
 private RuntimeException notFound(String r,String id){return new ResourceNotFoundException(r+" not found: "+id);} public static class ResourceNotFoundException extends RuntimeException{public ResourceNotFoundException(String m){super(m);}} public static class BusinessRuleException extends RuntimeException{private final String code;public BusinessRuleException(String c,String m){super(m);code=c;}public String getCode(){return code;}}
}
